---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted-deployment
spec:
  selector:
      matchLabels:
        app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontend
          image: frontend-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort