- hosts: all
  become: yes
  roles:
    - role: geerlingguy.java
      become: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
    - name: Install tools
      become: true
      apt:
        pkg:
        - nodejs
        - npm
        - git
    - name: Clone repository
      git:
        repo: https://github.com/bartoszgralek/webapp-vagrant.git
        dest: /home/vagrant/webapp-vagrant/
        version: 'master'
    - name: Create a m2 directory if it does not exist
      file:
        path: /home/vagrant/.m2
        state: directory
        mode: '0755'
    - name: Give ownership to vagrant
      file:
        path: /home/vagrant/.m2
        owner: vagrant
        group: vagrant
    - name: Give execute to start-backend.sh
      file:
        path: '/home/vagrant/webapp-vagrant/backend/start-backend.sh'
        state: file
        owner: vagrant
        group: vagrant
        mode: '0555'
    - name: Copy backend.service to systemd
      copy:
        src: /home/vagrant/webapp-vagrant/services/backend.service
        dest: /etc/systemd/system
        owner: vagrant
        group: vagrant
        remote_src: true
        mode: '0555'
    - name: Run service
      systemd:
        state: started
        name: backend
