- hosts: all
  become: yes
  roles:
    - role: geerlingguy.java
      become: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
    - name: Install tools
      become: true
      apt:
        pkg:
        - nodejs
        - npm
        - git
    - name: Clone repository
      git:
        repo: https://github.com/bartoszgralek/webapp-vagrant.git
        dest: /home/vagrant/webapp-vagrant/
        version: 'vagrant-test'
    - name: Create a m2 directory if it does not exist
      file:
        path: /home/vagrant/.m2
        state: directory
        mode: '0755'
    - name: Give ownership to vagrant
      file:
        path: /home/vagrant/.m2
        owner: vagrant
        group: vagrant
