- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
    - name: Setup
      become: true
      shell: 'curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -'
    - name: Fix packages
      become: true
      apt:
        state: fixed
    - name: Install tools
      become: true
      apt:
        pkg:
        - nodejs
        - git
    - name: Clone repository
      git:
        repo: https://github.com/bartoszgralek/webapp-vagrant.git
        dest: /home/vagrant/webapp-vagrant/
        version: 'vagrant-test'
    - name: Install angular cli
      npm:
        name: '@angular/cli'
        global: yes
    - name: Install node packages
      npm:
        path: /home/vagrant/webapp-vagrant/frontend
    - name: Give execute to start-frontend.sh
      file:
        path: '/home/vagrant/webapp-vagrant/frontend/start-frontend.sh'
        state: file
        owner: vagrant
        group: vagrant
        mode: '0555'
    - name: Copy frontend.service to systemd
      copy:
        src: /home/vagrant/webapp-vagrant/services/frontend.service
        dest: /etc/systemd/system
        owner: vagrant
        group: vagrant
        mode: '0555'
    - name: Run service
      systemd:
        state: started
        name: frontend  

